[package]
name = "nav-mdp"
version = "0.1.0"
authors = ["noah <nomaxx117@gmail.com>"]
edition = "2018"

[features]
sim = []

[dependencies]
num = "0.3.1"
rand = "0.8.2"
plotters = "0.3.0"
plotters-backend = "0.3.0"

[dependencies.derive_more]
version = "0.99.11"

[dependencies.mdp]
path = "../mdp"