[package]
name = "nav-algo"
version = "0.1.0"
authors = ["noah <nomaxx117@gmail.com>"]
edition = "2018"

[features]
heap = []
mdp = []
a-star = ["heap"]

default = ["mdp", "a-star", "heap"]

[dependencies]
