[package]
name = "cameralot"
version = "0.1.0"
authors = ["noah <nomaxx117@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.libmonkey-sys]
path = "../libmonkey-sys"
features = ["cameralot"]